#! /usr/bin/env php

<?php

require 'vendor/autoload.php';

use Chriha\CliLog\Commands\TailCommand;
use Symfony\Component\Console\Application;

$app = new Application( 'Beautiful log file tailing.', '0.1' );
$app->add( new TailCommand() );

$app->run();
